server {
    listen 80;
    server_name storyscape.witeso.com;

    location = /favicon.ico { access_log off; log_not_found off; }
    location /static/ {
        root /var/lib/jenkins/workspace/StoryScape;  # Adjust the path accordingly
    }

    location / {
        include proxy_params;
        proxy_pass http://unix:/tmp/gunicorn_storyscape.sock;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}